[book]
authors = ["Brook Jeynes"]
language = "en"
multilingual = false
src = "src"
title = "CAB301 Algorithms and Complexity"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true

# book.toml
# [preprocessor.quiz]
