[book]
authors = ["Brook Jeynes"]
language = "en"
multilingual = false
src = "src"
title = "CAB301 Algorithms and Complexity"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
